# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GpOpC5YUS9psDGDGu20SAHERoJ-m915N
"""

import random

def roll_dice(num_dice):
    """Rolls a specified number of dice and returns their values."""
    return [random.randint(1, 6) for _ in range(num_dice)]

def get_number_of_dice():
    """Asks the user for the number of dice to roll and returns it."""
    while True:
        try:
            num_dice = int(input("How many dice do you want to roll? "))
            if num_dice > 0:
                return num_dice
            else:
                print("Please enter a positive number.")
        except ValueError:
            print("Please enter a valid integer.")

def main():
    print("Welcome to the Advanced Dice Roller!")

    while True:
        num_dice = get_number_of_dice()
        dice_values = roll_dice(num_dice)
        print("\nRolling The Dices...")
        print("The Values are :", *dice_values)
        print("Sum of the dice values:", sum(dice_values))

        roll_again = input("\nWould you like to roll the dices again? (yes/y or no/n): ").lower()
        if roll_again not in ["yes", "y"]:
            break

    print("Thank you for using the Advanced Dice Roller. Goodbye!")

if __name__ == "__main__":
    main()